apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4= 
  DB_PASSWORD: WVdSdGFXNHRjR0Z6YzNkdmNtUUs=
  DB_PATH_NOTE: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L25vdGUtbW9uZ28/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
