apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
data:
  mongo-url: mongo-service
  note-url: note-service
  behave-url: behave-service
  query-url: query-service
  event-bus-url: event-bus-service

---

apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4= 
  DB_PASSWORD: WVdSdGFXNHRjR0Z6YzNkdmNtUUs=
  DB_PATH_NOTE: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L25vdGUtbW9uZ28/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  DB_PATH_BEHAVE: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L2JlaGF2ZS1tb25nbz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  DB_PATH_QUERY: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L3F1ZXJ5LW1vbmdvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  DB_PATH_EVENT: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L2V2ZW50LW1vbmdvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-deployment
  labels:
    app: note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note
  template:
    metadata:
      labels:
        app: note
    spec:
      containers:
        - name: note-service
          image: shelldog/note:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30010
          env:
            - name: ENV
              value: "production"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30010"
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PATH_NOTE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  type: NodePort
  selector:
    app: note 
  ports:
    - protocol: TCP
      port: 30010
      targetPort: 30010
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus-service 
          image: shelldog/event-bus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          env:
            - name: ENV 
              value: "production"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30000"
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PATH_EVENT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: NOTE_EVENT_ROUTE 
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: note-url
            - name: NOTE_EVENT_PORT
              value: "30010"
            - name: BEHAVE_EVENT_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: behave-url
            - name: BEHAVE_EVENT_PORT
              value: "30020"
            - name: QUERY_EVENT_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: query-url
            - name: QUERY_EVENT_PORT
              value: "30030"
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-service
spec:
  type: NodePort
  selector:
    app: event-bus 
  ports:
    - protocol: TCP 
      port: 30000
      targetPort: 30000
      nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query 
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query-service
          image: shelldog/query:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30030
          env:
            - name: ENV
              value: "production"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30030"
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PATH_QUERY
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - protocol: TCP 
      port: 30030
      targetPort: 30030
      nodePort: 30030

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: behave-deployment
  labels:
    app: behave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behave
  template:
    metadata:
      labels:
        app: behave
    spec:
      containers:
        - name: behave-service
          image: shelldog/behave:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30020
          env:
            - name: ENV
              value: "production"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "30020"
            - name: DB_PATH
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PATH_BEHAVE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "30000"
---
apiVersion: v1
kind: Service
metadata:
  name: behave-service
spec:
  type: NodePort
  selector:
    app: behave
  ports:
    - protocol: TCP
      port: 30020
      targetPort: 30020
      nodePort: 30020
