apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4= 
  DB_PASSWORD: WVdSdGFXNHRjR0Z6YzNkdmNtUUs=
  DB_PATH_NOTE: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L25vdGUtbW9uZ28/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  DB_PATH_BEHAVE: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L2JlaGF2ZS1tb25nbz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  DB_PATH_QUERY: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L3F1ZXJ5LW1vbmdvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  DB_PATH_EVENT: bW9uZ29kYitzcnY6Ly9zaGVsbGRvZzpDb21wdXRlclNjaWVuY2UwQG5vdGVib29rLmd1ZXcyLm1vbmdvZGIubmV0L2V2ZW50LW1vbmdvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
