apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  labels:
    app: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query 
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query-service
          image: query-service-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6030
          env:
            - name: ENV
              value: "local"
            - name: ENTRY_POINT
              value: "k8s"
            - name: PORT
              value: "6030"
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: mongo-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-secret
                  key: DB_PASSWORD
            - name: EVENT_BUS_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: event-bus-url
            - name: EVENT_BUS_PORT
              value: "6000"
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - protocol: TCP 
      port: 6030
      targetPort: 6030
      nodePort: 30030
